### ISSUE TITLE
Objects with circular references may break express responses

### ISSUE THREAD

**Issue by rangelfinal** [nxtep-io/ts-framework#17]
As `JSON.stringify` is used to parse the response to be sent by express, the method `response.json` throws when you try to send an object with circular references.
[Node provides the function `inspect` as an `util`](https://nodejs.org/api/util.html#util_util_inspect_object_options) that stringify the object, resolving circular references.

A proposed solution would be to change the following line
https://github.com/nxtep-io/ts-framework/blob/41c23df2878baa7b94eebb591c178fcffcc1d370/lib/components/helpers/response.ts#L63
to
`res.status(HttpSuccess.OK).json(util.inspect(d, { depth: null })`
as `depth: null` will deep stringify the object (The default is to ignore everything below the 2nd level)

**Comment by luiseduardobrito** [comment]
Maybe `util.inspect`  is not the best solution, as stated in the docs:

     The util.inspect() method returns a string representation of object that is intended for debugging. The output of util.inspect may change at any time and should not be depended upon programmatically. 

We need something like this -> https://github.com/WebReflection/circular-json

**Comment by luiseduardobrito** [comment]
One other solution is using a independent and reliable fork of the `util.inspect` method as the one from Automattic (creators of WordPress).

https://github.com/Automattic/util-inspect

**Comment by rangelfinal** [comment]
Flatted is "The future of [circular-reference] module", it's only 3 kilobytes (0,5 minified and gziped) and activelly mantained (Even has typings)
https://github.com/WebReflection/flatted#flatted

**Comment by rangelfinal** [comment]
Flatted and circular-json both output a custom format that's not compatible with common JSON.  
Instead, I opted to use [fclone](https://www.npmjs.com/package/fclone), which only clones an object, transforming any circular references in the string `'[Circular]'` (And it's also really fast and 1.2kb minified)

**Comment by luiseduardobrito** [comment]
We should try to sanitize the output, removing this `[Circular]` strings before rendering the JSON.

**Comment by rangelfinal** [comment]
We can fork the fclone project, it's really simple and stable (No commits for 2 years+, no deps, 0 open issues, 400k + weekly downloads), so it would be a one time change   

We would only need to change the line
`copy[i] = ~refs.indexOf(obj[i]) ? '[Circular]' : fclone(obj[i], refs);`
to
`copy[i] = ~refs.indexOf(obj[i]) ? undefined : fclone(obj[i], refs);`
on
https://github.com/soyuka/fclone/blob/797c64a1625a9123be93f8bb1e7374cab1419ff9/src/fclone.js#L36

and change the line
`copy[k] = ~refs.indexOf(obj[k]) ? '[Circular]' : fclone(obj[k], refs);`
to
`copy[k] = ~refs.indexOf(obj[k]) ? undefined : fclone(obj[k], refs);`
on
https://github.com/soyuka/fclone/blob/797c64a1625a9123be93f8bb1e7374cab1419ff9/src/fclone.js#L57
